server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:application_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  ## H2 Web Console is enabled and available at
  ## http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
      path: /h2